# Generated by Django 4.1 on 2022-08-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_contact_downloaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='downloaded_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
