# Generated by Django 4.1 on 2022-08-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_contact_downloaded_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='facilities/featured_images')),
                ('title', models.CharField(max_length=150)),
                ('staff_count', models.CharField(max_length=100)),
            ],
        ),
    ]
