# Generated by Django 4.1 on 2022-08-10 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_facility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facility/gallery/')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.facility')),
            ],
            options={
                'verbose_name_plural': 'gallery',
                'db_table': 'places_gallery',
            },
        ),
    ]
