# Generated by Django 4.1 on 2022-08-10 09:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_facility_options_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hod/image/')),
                ('name', models.CharField(max_length=200)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='teacher/image/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.departmenthod')),
            ],
        ),
    ]
