# Generated by Django 4.1 on 2022-08-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_departmenthod_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepartmentHod',
            new_name='Department',
        ),
    ]
