# Generated by Django 4.1 on 2022-08-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_departmenthod_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='designation',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='short_title',
            field=models.CharField(default='j', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='title',
            field=models.CharField(default='jjf', max_length=200),
            preserve_default=False,
        ),
    ]
