# Generated by Django 4.1 on 2022-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_department_designation_department_short_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='designation',
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(default='gd', max_length=200),
            preserve_default=False,
        ),
    ]
