# Generated by Django 4.1 on 2022-08-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_department_designation_teacher_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='year',
            field=models.CharField(default='3 Years - 6 Semesters', max_length=100),
            preserve_default=False,
        ),
    ]
