# Generated by Django 4.1 on 2022-08-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_department_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='event/featured_image/')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event/gallery/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.event')),
            ],
            options={
                'verbose_name_plural': 'Event Gallery',
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterModelTable(
            name='gallery',
            table=None,
        ),
    ]
