# Generated by Django 4.1 on 2022-08-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_event_eventgallery_delete_course_alter_gallery_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestevent',
            name='image',
        ),
    ]
