# Generated by Django 4.1 on 2022-08-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_latestevent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegenew',
            name='image',
        ),
        migrations.AddField(
            model_name='latestevent',
            name='image',
            field=models.ImageField(default='hh', upload_to='Latest_event/'),
            preserve_default=False,
        ),
    ]
